spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/userdb?useSSL=false"
    username: "root"
    password: "password"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
security:
  basic:
    enabled: false
    
server:
  port: 8081
 